apiVersion: v2
name: objects
description: A Helm chart for Objects API

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: postgresql
    version: ~10.2.0
    repository: https://charts.bitnami.com/bitnami
    tags:
      - postgresql
