version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    versioning-strategy: "auto"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
    groups:
      npm-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "pip"
    directory: "/requirements"
    versioning-strategy: "auto"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
    groups:
      pypi-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "ci.txt"
        update-types:
          - "minor"
          - "patch"
