version: '3'

services:
  db:
    # NOTE: No persistance storage configured.
    # See: https://hub.docker.com/_/postgres/
    image: postgis/postgis:12-2.5
    environment:
      - POSTGRES_USER=${DB_USER:-objects}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-objects}

  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes"]

  web:
    build: &web_build
      context: .
    environment: &web_env
      - DJANGO_SETTINGS_MODULE=objects.conf.docker
      - SECRET_KEY=${SECRET_KEY:-1(@f(-6s_u(5fd&1sg^uvu2s(c-9sapw)1era8q&)g)h@cwxxg}
      - OBJECTS_SUPERUSER_USERNAME=admin
      - OBJECTS_SUPERUSER_PASSWORD=admin
      - OBJECTS_SUPERUSER_EMAIL=admin@localhost
      - IS_HTTPS=no
      - ALLOWED_HOSTS=*
      - CACHE_DEFAULT=redis:6379/0
      - CACHE_AXES=redis:6379/0
      - CACHE_OIDC=redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - CELERY_LOGLEVEL=DEBUG
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    volumes: &web_volumes
      - media:/app/media  # Shared media volume to get access to saved OAS files

  celery:
    build: *web_build
    environment: *web_env
    command: /celery_worker.sh
    depends_on:
      - db
      - redis
    volumes: *web_volumes

  celery-flower:
    build: *web_build
    environment: *web_env
    command: /celery_flower.sh
    ports:
      - 5555:5555
    depends_on:
      - redis
      - celery

volumes:
  media:
