name: Check Open API Framework Version

on:
  push:
    branches:
      - master
    tags:
      - '*'
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 1'


jobs:
  open-api-workflow-check-oas:
    uses: maykinmedia/open-api-workflows/.github/workflows/oaf-check.yml@feature/udate-oaf-pr

    with:
      python-version: '3.11'
