name: quick-start

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Download docker-compose file
        run: wget https://raw.githubusercontent.com/maykinmedia/objects-api/master/docker-compose-quickstart.yml -O docker-compose-qs.yml
      - name: Start docker containers
        run: docker-compose -f docker-compose-qs.yml up -d
      - name: Wait until DB container starts
        run: sleep 10
      - name: Load fixtures
        run: docker-compose -f docker-compose-qs.yml exec -T web src/manage.py loaddata demodata
